### ISSUE TITLE
Provide snippets as completionItems

### ISSUE THREAD

**Issue by tahabasri** [tahabasri/snippets#1]
Provide snippets as completionItems (to be shown next to the built-in snippets using ctrl+space).
  - When initializing the application, we can successfully populate VSCode with snippets prefixed with `snp:snippet-label`
  - Problem starts to show up when we update existing snippets as the code bellow do not override existing ones but duplicate them:
```typescript
// see https://code.visualstudio.com/api/references/vscode-api#DocumentSelector
this.context.subscriptions.push(vscode.languages.registerCompletionItemProvider(
    '*', {
    provideCompletionItems() {
        return [
            {
                // see https://code.visualstudio.com/api/references/vscode-api#DocumentFilter
                label: `snp:${element.label.replace('\n', '').replace(' ', '-')}`,
                insertText: new vscode.SnippetString(element.value),
                detail: element.label,
                kind: vscode.CompletionItemKind.Snippet,
            },
        ];
    },
},
    // '' trigger character
));

// list completionItems
const list: any = await vscode.commands.executeCommand('vscode.executeCompletionItemProvider',
    vscode.window.activeTextEditor?.document.uri,
    new vscode.Position(0, 0));
console.log(list.items);
```

**Comment by LucaGabi** [comment]
I think you need to keep the value returned by the registration function, it is a disposable, you can call to remove the old provider and recreate the new one as above. 

Great work just this small thing missing.

**Comment by tahabasri** [comment]
Thanks @LucaGabi for the contribution ! It didn't come to my mind to go with that solution, great tip ! I added some tweaks in order to trigger the suggestions in all file types :
- because there is no explicit trigger character, VSCode uses default behavior which doesn't show up Snippet completion items for other file types (e.g js or json). VSCode suggestions ranking seems showing more language related candidates ([see this for more details](https://stackoverflow.com/questions/55693604/vscode-is-not-showing-custom-completion-suggestion-if-cursor-is-positioned-on-sp#comment98076893_55693604))

Thus, I'm setting the character `>` as main trigger (ctrl+space is always available but ranking may play with the results).
