### ISSUE TITLE
Error creating Snippets with Placeholders

### ISSUE THREAD

**Issue by carlosmgilp** [tahabasri/snippets#102]
Hi how are you.
Thanks for this great extension.

When trying to create a snippets with Placeholders nothing happens.
For example: I want my snippet to look like this.
(getcname "circle")
Where the word circle is the one that will vary.

I tried to do it this way and it didn't work.
(getcname "${1:Command}")
Also try doing it without the quotes. But it didn't work either.
(getcname ${1:Command})

The snippets created in previous versions are working.
It doesn't work now that I'm creating new snippets.

AutoCAD 2025
Visual Studio Code 1.87.2
Snippets 3.1.0
Windows 10
Language AutoLISP

Thank you and excuse my English, I only speak Spanish.

**Comment by tahabasri** [comment]
Thanks @carlosmgilp for reaching out, you should enable the option **Resolve Snippet Syntax** like the screenshot, this feature was enabled by default for new snippets but I turned it off as the majority of users expressed their preference having it disabled. You can access this option by right clicking the snippet and hit **Edit Snippet**.
Feel free to reopen this issue if this doesn't resolve your problem.
![image](https://github.com/tahabasri/snippets/assets/12661966/8f129d49-8581-49a9-8edf-d117a036e4aa)
