### ISSUE TITLE
Snippets not saved permanently and not synchronized when using vsc in multiple windows!

### ISSUE THREAD

**Issue by gignupg** [tahabasri/snippets#11]
To reproduce this bug: 

1. Close all vsc windows.
2. Open vsc in a new window.
3. Open a second vsc window. Now you should have two vsc windows open.
4. Create a snippet in one of the windows.
5. Switch to the other vsc window and click the refresh snippets button.
6. No snippets show up. It is impossible to see or access the snippet created in the other vsc window.
7. Create a snippet in the current vsc window. You should have one snippet in each of the vsc windows now.
8. Close all vsc windows.
9. Open a new vsc window.
10. Only one of the two snippets has been saved and can be accessed. The other snippet is lost.

**Comment by tahabasri** [comment]
@gignupg thanks for the catch ! Issue fixed with https://github.com/tahabasri/snippets/pull/16, this uses a classic `fs.watchFile` on the snippets JSON file, we should keep an eye on the performance and/or any issues related to this. This fix will be included in the upcoming release.
