### ISSUE TITLE
command 'snippetsCmd.addSnippet' not found

### ISSUE THREAD

**Issue by MarinAngelo** [tahabasri/snippets#18]
snippets path is not a valid JSON file, will revert back to... 
command 'snippetsCmd.addSnippet' not found

**Comment by tahabasri** [comment]
Thanks for reporting this ! Any steps to reproduce ?

**Comment by MarinAngelo** [comment]
I just click any button or symbol in the menue of your extension, nothing happens exept the error msg is apearing

**Comment by DerSchmaik** [comment]
Yeah I have the same Problem. I can't make new Snippets on a fresh Installation. First it also says `snippets path is not a valid JSON file, will revert back to...` Then when I tap on 'Add Snippet' or 'Add Snippet Folder' nothing happens and if I try to make one from the Clipboard it just shows the same error message: `command 'snippetsCmd.addSnippet' not found` 

My versions:
```
Version: 1.55.1 (user setup)
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042
```

Hope that helps

**Comment by platproit** [comment]
same issue. i even tried to change to the original patch/ uninstall reinstall/ take the settings.json line of code pointing to desired path hoping it would repopulate if i uninstalled and reinstalled. All my efforts to set back to default end in the same error message as above. I develop on WSL windows sub-system for Linux so this isn't anything new for me but really love this extension and hope to find a proverbial reset to default. thx for the awesome extension.
![Screenshot 2021-04-13 182107](https://user-images.githubusercontent.com/69649398/114632823-0f86ad80-9c85-11eb-928a-50ebbceba92f.png)
![Screenshot 2021-04-13 182208](https://user-images.githubusercontent.com/69649398/114632911-30e79980-9c85-11eb-9a36-4efcc0fc90e5.png)
![Screenshot 2021-04-13 182526](https://user-images.githubusercontent.com/69649398/114633157-a489a680-9c85-11eb-8f50-28ab4e7a198d.png)
![Screenshot 2021-04-13 182842](https://user-images.githubusercontent.com/69649398/114633437-18c44a00-9c86-11eb-8b37-f8f418576f43.png)

**Comment by platproit** [comment]
# Clarification to my Confusion

## So i found the disconnect and why once i changed the path of ```data.json``` the extension started throwing errors and i couldn't get it to work no matter how i maneuvered the installation, file, or even so far as to clone the repo in search of a remedy. 

### There didn't seem to be any reference of this specifically in the ```README.md```. Although i do typically just skim through the ```README.md```. 

#### Anyways... you have to have your ``` data.json ``` file in the same folder as your ```global vs-code snippets file```. 
```PATH
c:\\Users\\alias\\AppData\\Roaming\\Code\\User\\snippets\\random_name.code-snippets

// fyi this is not the same as the automated default path that sets if the path listed is not to an accessible .json file,
thus causing the extension to default to a non-existent file path and creating the confusion and errors.//


```
#### In my case the folder i needed was not in the ```globalStorage``` folder but in the same level directory branch  as ```globalStorage```. 

#### So if you misinterpreted the ```README``` as i did from what i can understand is as long as your ```data.json``` and ```.code-snippets``` file for vs-code are in the same folder the error messages should clear up and should allow you to access your snippets in all workspaces you develop in as long as it is within vs-code.

##### Also i would like to apologize in advance for my example looking like my 7 year old marked it up for me...….. ">.> he totally did >.>
![Screenshot 2021-04-13 230718](https://user-images.githubusercontent.com/69649398/114655514-f516f900-9cb1-11eb-8380-99cef6b844f9.png)

**Comment by broven** [comment]
same, this is context
![image](https://user-images.githubusercontent.com/12854613/115184311-21969f00-a110-11eb-8918-983f1f40e220.png)

**Comment by tahabasri** [comment]
Okay, I guess I see the issue : `context.globalStorageUri` guaranties that **parent** folder `.../globalStorage` is available but not the folder with extension name. This should be created by the app. I should push a fix ASAP.

**Comment by tahabasri** [comment]
Fixed with https://github.com/tahabasri/snippets/pull/20
