### ISSUE TITLE
Snippet organization.

### ISSUE THREAD

**Issue by carlosmgilp** [tahabasri/snippets#22]
Hi, how are you.
You could add organization methods for the Snippets.
Sort snippets alphabetically by folder or all.
Move between folders.
Move Snippets manually with the pointer.
Collapse all and expand all.

![image](https://user-images.githubusercontent.com/80189444/116423704-edf1fe00-a80e-11eb-91df-c6451c6db798.png)

Thanks.

**Comment by tahabasri** [comment]
@carlosmgilp drag and drop support is available with latest release 3.0.0 👍🏼

**Comment by tahabasri** [comment]
@carlosmgilp sorting [A-Z] has been added to release 3.1.0.
