### ISSUE TITLE
Edit Snippet - Move to Folder

### ISSUE THREAD

**Issue by CynicalWilson** [tahabasri/snippets#26]
It'd be great to be able to move existing snippets to newly created or existing folders

**Comment by tanphat110699** [comment]
@tahabasri Will this feature come with the next update? I created many of snippet and cant move them to a new folder. 

Your extension is the best i can find. Thank for your effort, my lord!

**Comment by tahabasri** [comment]
@CynicalWilson @tanphat110699 drag and drop support is available with latest release 3.0.0 👍🏼
