### ISSUE TITLE
Search for snippet

### ISSUE THREAD

**Issue by maxwinkler13** [tahabasri/snippets#27]
Is there (or planned) a feature that allows you to search for snippets across all folders, or within a specific folder? Maybe, and that'd be just perfect, via description text but also via tags (which would be another sweet feature)

**Comment by tahabasri** [comment]
You can search for Snippets via keyword using command **Snippets: Open Snippet**.
![image](https://user-images.githubusercontent.com/12661966/126906894-a54fbe39-47dc-4b9b-878e-f6d0916648a4.png)

> within a specific folder?

not sure if that's necessary to implement as you can just refine your search query in the previously mentioned command.

> via description text but also via tags

The same command above searches in snippets titles and in their descriptions. Tags are very helpful for better organization, I just can't think currently of a way to implement it in the best way possible. I don't want to clutter the tree view with lot of UI elements.
