### ISSUE TITLE
"snippets.snippetsLocation" URI warning

### ISSUE THREAD

**Issue by saiballo** [tahabasri/snippets#28]
I'm on linux and I have set "snippets.snippetsLocation" value as:

"~/.config/Code/User/globalStorage/tahabasri.snippets/data.json"

I recive this warning in settings.json:

"String is not a URI: URI with a scheme is expected."

**Comment by tahabasri** [comment]
Given the increased number of issues related to managing snippets in file system. Please consider upcoming version which will use VSCode internal APIs to store snippets instead of an external JSON file.

PR : #29
