### ISSUE TITLE
Backup or export snippets

### ISSUE THREAD

**Issue by muoto** [tahabasri/snippets#3]
How can I back up or export snippets (what folder are they located in)...by the way fantastic extensions, I love it!

**Comment by FatehAK** [comment]
You could do a manual backup. I used this way to transfer my snippets across laptops. On a macos the snippets json is located in this folder:
`/Users/$user/Library/Application Support/Code/User/globalStorage/tahabasri.snippets`

**Comment by muoto** [comment]
By default, when i open the snippets tab, all the snippets are expanded and there is no easy way to minimize all....

**Comment by muoto** [comment]
On a PC the location of the snippet is:

`C:\Users\$user\AppData\Roaming\Code\User\globalStorage\tahabasri.snippets`

**Comment by tahabasri** [comment]
@muoto thanks for the feedback ! New feature for changing default snippets location has been added and will be available with upcoming release. See https://github.com/tahabasri/snippets/issues/7. You can use this feature to target a directory in Cloud or with a remote server and ensure a backup of your snippets.
