### ISSUE TITLE
Manual backup

### ISSUE THREAD

**Issue by carlosmgilp** [tahabasri/snippets#34]
Hi how are you.
I have the latest version of snippets installed, but now I can't get the backup file.  Currently I work on two computers, but I do not have internet, I would like to be able to back up my snippets manually so that I can use it on both computers.  How finger to do it.
Thanks.

**Comment by tahabasri** [comment]
Hi, you have currently two options :
- either use 1.x version of Snippets and keep same routine you had before (you'll miss on new updates/features)
- or use option `snippets.useWorkspaceFolder` which will let you manage snippets in file `./vscode/snippets.json` which is **relative** to your open workspace in VSCode. But that will require you to synchronize that file across multiple workspaces.
