### ISSUE TITLE
Import and export snippets

### ISSUE THREAD

**Issue by carlosmgilp** [tahabasri/snippets#36]
Please give an option that allows you to import and export the created snippets.
Thanks.

**Comment by tahabasri** [comment]
On backlog for upcoming version 👍🏼

**Comment by carlosmgilp** [comment]
Please don't forget about this upgrade.

**Comment by tahabasri** [comment]
[snippets-2.2.0.zip](https://github.com/tahabasri/snippets/files/7756866/snippets-2.2.0.zip)

PR opened including all changes necessary for this feature. I'm attaching a preview build so we can test it before publishing it with the upcoming release. An assist from your side will be much appreciated.

**Comment by carlosmgilp** [comment]
Hello Brother, how are you?
Thanks for your help.
At night when I get home I do the tests.
Greetings.

**Comment by tahabasri** [comment]
Thanks @carlosmgilp for the assistance, I'll do more tests from my side before promoting this for next release 👍🏼
