### ISSUE TITLE
Language scope for snippets

### ISSUE THREAD

**Issue by ArzkaTheCoder** [tahabasri/snippets#38]
First, thanks for the great extension! Just one feature that I really miss: Language scope for snippets.

Right now, all snippets work "globally" (with any coding language / file extension). But I don't want Javascript snippets to be suggested when I'm writing CSS... Or Python snippets to be suggested when I'm writing C#... Etc...

So it would be great to be able to define language scope for each snippet. Default scope could be the same file extension that is currently opened in VS Code.

(This is likely not a problem for those who prefer to pick snippets with mouse (there can be separate snippet folders for different programming languages), but I prefer to select snippet by using keyboard (by writing ">" + snippet name).)

**Comment by tahabasri** [comment]
@ArzkaTheCoder Going back to this feedback from time to time and now I have a suggestion that may keep the extension simple (as it was intended to be) and support this.
- Will try to add support for language scope for folders (to keep it simple)
- Choose file extensions for which folder snippets will show up
- When triggering '>', snippets for only filtered scope will popup

This is not that simple ofc as we initialize snippets as suggestions at extension loading time, maybe re-filtering by language scope can be done after opening target file but I'm not sure about performance then. Will let you know of my findings ASAP.

Thanks btw for the feedback!

**Comment by tahabasri** [comment]
@ArzkaTheCoder language scope finally added to Snippets, release 3.1.0 will: 
- auto detect language from current document (Snippet extracted from active editor)
- auto detect language from name if extension appended, e.g append .js to the name to create Javascript snippet
- show snippets based on languages, Snippets not tight to a language will be displayed in plaintext editors (VSCode default for new windows)
- offer possibility to edit Snippet and force a specific language (will display all languages installed locally)
- show language specific language natively next to the Snippet
