### ISSUE TITLE
Separate setting for disabling magic key and intellisense

### ISSUE THREAD

**Issue by ryanmcfall** [tahabasri/snippets#39]
Consider the following common action when editing HTML
*  Type &lt;p&gt;
*  Press Enter to put content of the &lt;p&gt; element on its own line

Currently if I do this, typing the &gt; key gives a list of suggested snippets, and the Enter key will insert the contents of the first snippet in the list.

I can fix this by changing the setting to disable the magic key, but that is also tied to whether or not snippets are suggested by Intellisense.  I would love to be able to enable/disable these two things separately.  Another option would be to add a setting that allows me to change the magic key from &gt; to something else.  I don't think there is such a setting.

**Comment by tahabasri** [comment]
Fixed in https://github.com/tahabasri/snippets/pull/43
