### ISSUE TITLE
[Feature request] Scope snippets based on file extension

### ISSUE THREAD

**Issue by ItsCubeTime** [tahabasri/snippets#4]
Make snippets categorize to only be exposed on a per file extension basis to prevent snippets created for lets say Python to show up in the ctrl+space menu when working in a .cpp file.

Or is this a thing already? The docs doesn't seem to mention it

**Comment by tahabasri** [comment]
That was exactly the problem my extension originally tried to solve. [There are multiple extensions](https://marketplace.visualstudio.com/search?term=snippet&target=VSCode&category=All%20categories&sortBy=Relevance) now for dealing with snippets dedicated for a language or a file extension, which limit their usability. I believe that developing a "generic" treeView for all your snippets will offer you the flexibility to organize snippets the way you prefer. No default or strict way of doing it !
