### ISSUE TITLE
Feature to drag snippets to reorder them

### ISSUE THREAD

**Issue by CuriousDrive** [tahabasri/snippets#40]
I have just started using Snippets and loving it,

I think it will be nice to drag snippets to reorder them.

**Comment by tahabasri** [comment]
This is related to https://github.com/tahabasri/snippets/issues/2

**Comment by CuriousDrive** [comment]
Closing this issue

**Comment by tahabasri** [comment]
@CuriousDrive drag and drop support is available with latest release 3.0.0 👍🏼
