### ISSUE TITLE
Support prefix

### ISSUE THREAD

**Issue by chrisgoffinet** [tahabasri/snippets#42]
Just like when defining User Snippets in VSCode, it would be helpful if this extension supported `prefix`.

```
{
    "Insert heading level 1": {
       "prefix": "heading1",
       "body": ["# ${1:${TM_SELECTED_TEXT}}$0"],
       "description" : "Insert heading level 1"
    }
}
```

> The `prefix` property defines the trigger phrase for the snippet. It can be a string or an array of strings (if you want multiple trigger phrases). Substring matching is performed on prefixes, so in this case, typing "h1" would match our example snippet.

**Comment by tahabasri** [comment]
@chrisgoffinet took more than a year to respond to this :D
I finally added prefix support. Edit your snippets and you'll see the new option:
![image](https://github.com/tahabasri/snippets/assets/12661966/e6514b30-594d-4650-b03d-390ba5d6e4ad)
Once you save the snippet, just start typing that prefix and its suggestion will popup:
![image](https://github.com/tahabasri/snippets/assets/12661966/6650c75b-df3e-4f33-b95a-f7d77c5f1747)
The prefix will be camelized automatically (`awesome snippet` => `awesomeSnippet`). Other fixes have been implemented to show suggestions on all file formats and adding couple of settings for advanced users (like you).
