### ISSUE TITLE
When using a snipped with $ in it, it will be omitted

### ISSUE THREAD

**Issue by dariovolaricbasis** [tahabasri/snippets#46]
For example create a snippet of this:
watch: {
  $route(to) {
    this.trackPage(to.fullPath);
  }
},
When using this snipped the $ will be omitted.

**Comment by tahabasri** [comment]
Thanks for the feedback @dariovolaricbasis !

Snippets syntax resolving is enabled by default. To disable that, disable following checkbox in the edit snippet window.

![image](https://user-images.githubusercontent.com/12661966/181302142-29b9a39b-fb4e-48a5-a86a-46d29a0f7512.png)
