### ISSUE TITLE
Request for sorting of snippet

### ISSUE THREAD

**Issue by hamohd70** [tahabasri/snippets#47]
I liked the extension. Thank you very much.
I also would like to request a sorting of snippet function. this would make it easier to locate the snippet.

**Comment by tahabasri** [comment]
@hamohd70 what sort options you'd suggest? A-Z only? Issue here is that you may lose original order.

**Comment by hamohd70** [comment]
yes it is  A-Z only.
lose original order? If possible, this can be an option. with many
snippets, it will be hard to locate one.

**Comment by tahabasri** [comment]
It's possible to keep a record of original order after reordering to A-Z, complications will happen after you start moving snippets in and out using the new Drag and Drop feature. Thus, implementing A-Z order will/should imply losing original order of snippets before hitting A-Z button, will work on this then 👍🏼.

**Comment by hamohd70** [comment]
Thanks taha and best of luck

**Comment by tahabasri** [comment]
@hamohd70 support for sorting added to release 3.1.0, you'll be able to sort:
- folder items [A-Z]
- full tree of Snippets [A-Z]
Original order is lost, custom reordering is always possible using up and down arrows.
