### ISSUE TITLE
Add organization ability

### ISSUE THREAD

**Issue by JNewstedt** [tahabasri/snippets#50]
I'd like to see the ability to drag-n-drop snippets into pre-existing folders I've created to clean that area up. (I have a LOT of snippets.)
If I create a snippet and then create a folder, I can't drag that snippet into that folder to organize the panel better. When I highlight a snippet in the panel, the only option is to move them up and down using the arrows one position at a time. You can't just drag it into the folder. (See image.) 

![image](https://user-images.githubusercontent.com/91703537/194637834-0c0fc9ad-9e2a-46fd-b463-176f29395bfa.png)

**Comment by tahabasri** [comment]
@JNewstedt drag and drop support is available with latest release 3.0.0 👍🏼

**Comment by tahabasri** [comment]
@JNewstedt also sorting [A-Z] has been added to 3.1.0 too. That may help to better organize snippets.
