### ISSUE TITLE
Enhancements 🎨

### ISSUE THREAD

**Issue by ayoubkhan558** [tahabasri/snippets#51]
I really love the plugin, But here are some suggestions for you.
I think these are necessary for this plugin and surely improve the overall experience. 

- ✅ Please add ICON support for folders 📂.
- ✅ Add Icon support for files, Ability to add extensions for files.
- ✅ Syntax Highlighting for code snippets.

**Comment by tahabasri** [comment]
@ayoubkhan558 thanks for your feedback, took too long to work on this (not much free time). Snippets 3.1.0 will support:
- Icons for folders ✔️
- Language scope for Snippets (icon for each language) ✔️
