### ISSUE TITLE
Can I publish a set of snippets to VS Code

### ISSUE THREAD

**Issue by louiss0** [tahabasri/snippets#55]
I'd like to create a set of snippets of code for `.astro` files but publishing them would be a pain. Can you please allow me to publish them to vs code. Thanks.

**Comment by tahabasri** [comment]
Hey @louiss0, I still don't have a clear vision about this request, can you share more details about what you want to achieve and what limitations the extension has regarding that. Thanks!

**Comment by louiss0** [comment]
> Hey @louiss0, I still don't have a clear vision about this request, can you share more details about what you want to achieve and what limitations the extension has regarding that. Thanks!

Never mind
