### ISSUE TITLE
Drag to organize import

### ISSUE THREAD

**Issue by darylshy** [tahabasri/snippets#56]
Hi, 
Your Snippets extension is one of my new favorites! Thank you for creating it. It will help my productivity by a mile. 
I did, however, need help organizing my snippets after creating them. I had a bunch of snippets I copied over from my user snippets, and they needed to be more organized initially. I thought I could port them over, then sort them later. Unfortunately, that was not the case. I had to spend a lot of time recopying those snippets and pasting them from the clipboard into a folder. Please take a look at the video below. This was very time-consuming. I would love to see a drag-to-organize feature in an upcoming update. 

https://user-images.githubusercontent.com/5904383/212477066-e21ed44e-974f-4f6e-9bac-a29cc37d4965.mov

**Comment by dawnlh** [comment]
I agree! It will be convenient to have a more flexible way to move existing snippets to another folder.

**Comment by tahabasri** [comment]
Matter of hours ...

**Comment by tahabasri** [comment]
@darylshy @dawnlh Thanks for your amazing feedback !
Support for drag and drop will be available in next update (release 3.0.0) 👍🏼
