### ISSUE TITLE
[Feature Request] Add possibility to preview the snippet with syntax highlighting

### ISSUE THREAD

**Issue by FatehAK** [tahabasri/snippets#6]
Great extension so far! Wonder why VS Code doesn't have this built in. As I was using the extension I observed the need to view the snippet before I paste it inside the editor. It would be cool if we had like an eye icon next to the snippet name in the sidebar which would allow us to preview the snippet on the fly.

This could come handy in cases where we sometimes don't want to copy the snippet, but just want to check it out as a form of example code.

**Comment by tahabasri** [comment]
@FatehAK thanks for the feedback ! I already added a tooltip when hovering :
![image](https://user-images.githubusercontent.com/12661966/114287625-32844800-9a60-11eb-9cee-8ed0a921ee6b.png)

But indeed, we can add something that will show the full snippet. One thing to consider, is that it should be a popup or something quick, opening a new tab for instance for only a preview is not that practical. I'll update with feedback once I check the possibilities.

**Comment by tahabasri** [comment]
Fixed by https://github.com/tahabasri/snippets/pull/77
@FatehAK tooltip expanded to show more content:
![image](https://github.com/tahabasri/snippets/assets/12661966/de7e59a7-0770-4d31-a6b5-4e64f4132c3d)
