### ISSUE TITLE
Potential bug while moving items using drag and drop

### ISSUE THREAD

**Issue by faseceroo** [tahabasri/snippets#62]
Hi, thanks for this extension,  the drag and drop feature is a win.

I have 10 folders containing aprox 100 snippets. I can keep adding snippets to existing folders but I can't add new snippets to folder 11. Every time I try, the folder remains empty.

**Comment by faseceroo** [comment]
Ok I fixed this, after restoring a copy previous to the bug. The error wa inside the json file. The **lastId** value was wrong, I had 91 items and **lastId** had a value of 76.

It looks like after deleting and drag and drop some files around the **lastId** value can get an incorrect value and cause issues.

**Comment by tahabasri** [comment]
@faseceroo there is a reproducible bug filed here #67, new release will add a troubleshooting button and bug fixes.
