### ISSUE TITLE
Feature request: Snippets' compatibility with native VS snippets

### ISSUE THREAD

**Issue by samuelmswong** [tahabasri/snippets#64]
Does this extension's json format support the "description" field?
VSCode's native snippet json format supports a "description" field - "an optional description of the snippet displayed by IntelliSense".
It manifests as grey descriptive text beside each snippet name in the dropdown box for suggested snippets. Example image below.
![image](https://user-images.githubusercontent.com/96700223/222492923-af2965f0-f09c-4d2b-948f-cc4837376162.png)
Is this "Snippets" extension able to make use of the same IntelliSense capability?

Alternatively/Additionally, a way to import/export between the native VSCode snippet format and this extension's format would make it smoother for people with existing snippets to use this extension and continue developing them. I suppose #42 comes from a similar line of thinking.

**Comment by tahabasri** [comment]
Thanks for the suggestion @samuelmswong I'll look into the possibilities of implementing such features and keep you updated.

**Comment by tahabasri** [comment]
@samuelmswong description field added with 3.1 release.
