### ISSUE TITLE
Same snippet different content

### ISSUE THREAD

**Issue by abrar2005** [tahabasri/snippets#66]
### Problem
Making different snippet names for different languages instead of it automatically checking the file type. If I want the same snippet name but with different content according to the file type it would just give me the same content

### Example
If I use 3 languages I would have to setup something like this for me to log the items: `>log-js` `>log-php` `>log-ts`

### Solution
While making the snippet user should be prompted with an input that lets him choose a language for the snippet. and while you are trying to use the snippet it should automatically check the file type and suggest snippets that match with the language.

**Comment by tahabasri** [comment]
@abrar2005 thanks for the feedback. The snippet was initially designed to be as generic as possible. Other users use the extension for things not Code related. I will for sure look into the possibility of supporting something like this in the future but that's not the priority.

**Comment by tahabasri** [comment]
@abrar2005 release 3.1.0 will support programming languages, please check the release changelog or [this issue](https://github.com/tahabasri/snippets/issues/38) for further details.
