### ISSUE TITLE
Drag and drop within a folder

### ISSUE THREAD

**Issue by carlosmgilp** [tahabasri/snippets#69]
Hello how have you been.
As always, thanks for your collaboration.
In this case, I'm telling you that I can drag and drop the snippets from one folder to another, but I can't drag and drop within the same folder.
This is a mistake?
Or is it planned to incorporate it in the future?
Thank you.

**Comment by tahabasri** [comment]
Hi @carlosmgilp thanks for your feedback, this is not supported up to now, currently, you can use the up and down arrows next to each snippet. I'll let you know once that drag and drop within same folder is implemented.

**Comment by tahabasri** [comment]
@carlosmgilp VSCode API is not helping us implementing such feature for now. Even VSCode own folders structure is not supporting dragging and dropping within same folder. Please rely on the 'up' and 'down' arrows for now. I'll update this issue whenever the API supports such mechanism. Thanks.
