### ISSUE TITLE
How to change the storage path?

### ISSUE THREAD

**Issue by Hexodus** [tahabasri/snippets#7]
I really like this extension because it's so simple to work with. The only thing that I wish for is to change the folder where the snippets are stored so I may sync them via dropbox or one drive.
Is it allready possible?

**Comment by daniel347x** [comment]
Agreed. This is the best snippets extension out there. I am being hobbled, though, in being able to use it due to the inability to sync (I use a number of remote SSH servers and each one maintains its own snippets file).

**Comment by CoffeeCrew** [comment]
+1
Do you guys, know the default path where the snippets are stored ?

**Comment by tahabasri** [comment]
@Hexodus @daniel347x thank you for the feedback ! Just added support for changing default snippets location. See https://github.com/tahabasri/snippets/pull/14 for details. This should be available with upcoming release.
