### ISSUE TITLE
Folders: more than 3?

### ISSUE THREAD

**Issue by Maxensation** [tahabasri/snippets#71]
Hi, 

First thing first, thank you for your extension : it is very convenient!!

Would like to know if there is a limitation with folders. I mean it is like we can create only 3  folders in a folder.
Is there a way to increase the amount of folders in a folder?

Max

**Comment by tahabasri** [comment]
Thanks @Maxensation for the question. You can create as much folders as you want.
![image](https://github.com/tahabasri/snippets/assets/12661966/82c42b0a-036b-452e-9b8e-cf858f10cd2a)

Please open this issue again if you are experiencing an issue with folders.
