### ISSUE TITLE
Edit Snippet should provide a VS Code Editor (or at least allow Usage of "tab")

### ISSUE THREAD

**Issue by LukasGold** [tahabasri/snippets#72]
Hey! Great work on this extensions! I really like that the extension recognizes the VS Code snippet syntax!

I was editing some snippet over the GUI you provided (right-click + "Edit Snippet") and wanted to create an indentation in a for loop. Unfortunately, pressing of "tab" selects the "Save" Button.

From the viewpoint of my use case, it would be great if the Snippet Content Text Box would be a potent editor with language recognition or at least allow the usage of "tab".

**Comment by tahabasri** [comment]
Thanks @LukasGold, indeed that's a much needed feature. I'll work on that ASAP.

**Comment by tahabasri** [comment]
Fixed by https://github.com/tahabasri/snippets/pull/76
@LukasGold added tab support within the text box. Adding support for full editor capabilities will require more effort. Sticking with default behavior now + tab support.

**Comment by LukasGold** [comment]
That's great news. Thank you!
