### ISSUE TITLE
escape $

### ISSUE THREAD

**Issue by delcon** [tahabasri/snippets#73]
I have not found any way to escape the following line of code
`this.$portal.$on('documentTouchClick', this.outsideClickFn)`

the vscode escape codes don't work
[https://code.visualstudio.com/docs/editor/userdefinedsnippets#_how-do-i-have-a-snippet-place-a-variable-in-the-pasted-script](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_how-do-i-have-a-snippet-place-a-variable-in-the-pasted-script)

**Comment by tahabasri** [comment]
Hey @delcon, please follow these steps:
- Right click on the snippet > Edit Snippet
- Uncheck `Resolve Snippet Syntax ` > Save
$ sign should be escaped.

**Comment by tahabasri** [comment]
Auto Syntax Resolving will be disabled by default starting on release 3.1
