### ISSUE TITLE
$符号插入到代码中 无法显示 被吃掉了 必须写 $$才能在前端输出一个$

### ISSUE THREAD

**Issue by BLACKSUZAKU** [tahabasri/snippets#8]
如题  ↑  我自定义函数 比如  $var = xxx  在snippets中保存后  点击 编辑器中只显示 var  前面那个 $  符号缺失 不知  $  是否是snippet的关键字还是怎么 ， 目前我只能在snippets中定义成   $$var=xxx   才能输出想要的结果；另， 如果定义中 有关键字  $!  则显示正常

**Comment by tahabasri** [comment]
Thanks for the feedback ! This is happening because we try to handle anything with dollar sign as a placeholder. I'll add a checkbox in the edit tab to manually enable/disable the resolving of placeholders.

**Comment by tahabasri** [comment]
Added support for explicitly enabling/disabling syntax resolving. See https://github.com/tahabasri/snippets/pull/15. This will be available in the upcoming release.
