### ISSUE TITLE
Snippets appear twice on suggestions

### ISSUE THREAD

**Issue by brpaz** [tahabasri/snippets#89]
Hello.

When I toggle my snippet suggestions `Ctrl + Space`,  all the snippets appear twice. In this example, the first two are manage by this extension.

![image](https://github.com/tahabasri/snippets/assets/184563/75c61957-710c-49cd-86e8-7a021b7640d3)

**Comment by brpaz** [comment]
The snippets are bound to a language (tested with YAML and Golang). It seems to be happening for all files.

But If I create a snippet without be tied to a language, it appears correctly, when I create a new file.

**Comment by tahabasri** [comment]
I can't reproduce this, I'll need more details on your setup if it's okay...
- Are the rest of the snippets coming from the out of the box VS Code settings (the Kubernetes ones)?
- Was this happening from day 1 (day 1 after having latest extension update)?
- Is this happening when trying to type the snippet name also ?

**Comment by tahabasri** [comment]
@brpaz please follow these steps in order to clean your snippets: https://github.com/tahabasri/snippets#known-issues
If the error still persists, feel free to reopen this issue with additional details.
