### ISSUE TITLE
Organize snippets

### ISSUE THREAD

**Issue by chapalee** [tahabasri/snippets#9]
Hello how are you.
You could improve the way you organize snippets and folders.
How to move snippets between folders.
Move folders on any branch.
If you can drag folders and snippets with the pointer, so much the better.
Thanks.

**Comment by tahabasri** [comment]
@chapalee thanks for the feedback. Most of these requested features would have been doable if they were offered by the Tree View API. There is a fairly popular request for drag and drop, for instance, here https://github.com/Microsoft/vscode/issues/32592

**Comment by tahabasri** [comment]
@chapalee drag and drop support is available with latest release 3.0.0 👍🏼
