### ISSUE TITLE
Snippet cannot be deleted

### ISSUE THREAD

**Issue by McYoda** [tahabasri/snippets#92]
I try to delete a snippet by right-clicking and "Delete Snippet" -> nothing happens.

**Comment by tahabasri** [comment]
@McYoda is that the only action not working ? Can you try other actions (deleting folder, creation/updating snippets). Thanks.

**Comment by tahabasri** [comment]
@McYoda please follow these steps in order to clean your snippets: https://github.com/tahabasri/snippets#known-issues
If the error still persists, feel free to reopen this issue with additional details.
